SELECT 
    A.AU_ID,
    A.AU_FNAME,
    A.AU_LNAME,
    B.BOOK_NUM,
    B.BOOK_TITLE
FROM 
    AUTHOR A
JOIN WRITES W ON A.AU_ID = W.AU_ID
JOIN BOOK B ON W.BOOK_NUM = B.BOOK_NUM
WHERE 
    B.BOOK_SUBJECT = 'Cloud'
ORDER BY 
    B.BOOK_TITLE,
    A.AU_LNAME;