SELECT 
    B.BOOK_NUM,
    B.BOOK_TITLE,
    COUNT(C.BOOK_NUM) AS `Times Checked Out`
FROM 
    BOOK B
LEFT JOIN CHECKOUT C 
    ON B.BOOK_NUM = C.BOOK_NUM
GROUP BY 
    B.BOOK_NUM, B.BOOK_TITLE
ORDER BY 
    COUNT(C.BOOK_NUM) DESC,
    B.BOOK_TITLE;