SELECT 
    A.AU_LNAME,
    A.AU_FNAME,
    B.BOOK_TITLE,
    B.BOOK_COST
FROM 
    AUTHOR A
JOIN WRITES W ON A.AU_ID = W.AU_ID
JOIN BOOK B ON W.BOOK_NUM = B.BOOK_NUM
ORDER BY 
    B.BOOK_NUM,
    A.AU_ID;