-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.SELECT 
SELECT
    (SELECT COUNT(*) FROM INVOICE) AS `TOTAL INVOICES`,
    (SELECT ROUND(SUM(LINE_UNITS * LINE_PRICE), 2) FROM LINE) AS `TOTAL SALES`,
    ROUND(MIN(CUSTOMER_TOTAL), 2) AS `MINIMUM CUSTOMER PURCHASES`,
    ROUND(MAX(CUSTOMER_TOTAL), 2) AS `LARGEST CUSTOMER PURCHASES`,
    ROUND(AVG(CUSTOMER_TOTAL), 2) AS `AVERAGE CUSTOMER PURCHASES`
FROM (
    SELECT
        I.CUS_CODE,
        SUM(L.LINE_UNITS * L.LINE_PRICE) AS CUSTOMER_TOTAL
    FROM INVOICE I
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
    GROUP BY I.CUS_CODE
) AS CUSTOMER_PURCHASES;