-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.SELECT 
SELECT
    COUNT(DISTINCT I.INV_NUMBER) AS `TOTAL INVOICES`,
    ROUND(SUM(L.LINE_UNITS * L.LINE_PRICE), 2) AS `TOTAL SALES`,
    ROUND(MIN(CUST_TOTALS.CUSTOMER_TOTAL), 2) AS `MINIMUM CUSTOMER PURCHASES`,
    ROUND(MAX(CUST_TOTALS.CUSTOMER_TOTAL), 2) AS `LARGEST CUSTOMER PURCHASES`,
    ROUND(AVG(CUST_TOTALS.CUSTOMER_TOTAL), 2) AS `AVERAGE CUSTOMER PURCHASES`
FROM INVOICE I
JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
JOIN (
    SELECT
        I.CUS_CODE,
        SUM(L.LINE_UNITS * L.LINE_PRICE) AS CUSTOMER_TOTAL
    FROM INVOICE I
    JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
    GROUP BY I.CUS_CODE
) CUST_TOTALS;