-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
SELECT ASSIGNMENT.EMP_NUM,EMPLOYEE.EMP_LNAME,
SUM(ASSIGNMENT.ASSIGN_HOURS) AS SUMOFASSIGN_HOURS,
SUM(ASSIGNMENT.ASSIGN_CHARGE) AS SUMOFASSIGN_CHARGE
FROM ASSIGNMENT, EMPLOYEE
WHERE ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
GROUP BY ASSIGNMENT.EMP_NUM, EMPLOYEE.EMP_LNAME
ORDER BY ASSIGNMENT.EMP_NUM;