-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
SELECT PROJ_NAME,PROJ_VALUE,PROJ_BALANCE,EMP_LNAME,EMP_FNAME,
EMP_INITIAL,JOB.JOB_CODE,JOB_DESCRIPTION,JOB_CHG_HOUR
FROM PROJECT
JOIN EMPLOYEE ON PROJECT.EMP_NUM = EMPLOYEE.EMP_NUM
JOIN JOB ON EMPLOYEE.JOB_CODE = JOB.JOB_CODE
ORDER BY EMP_LNAME;