-- Write your query below and then click "Run Query" to execute it. To save multiple queries, click the "+" icon on the left.
SELECT EMP_NUM,
EMP_LNAME,
SUM(ASSIGN_HOURS) AS SUMOFASSIGN_HOURS,
SUM(ASSIGN_CHARGE) AS SUMOFASSIGN_CHARGE
FROM ASSIGNMENT, EMPLOYEE
WHERE ASSIGNMENT.EMP_NUM = EMPLOYEE.EMP_NUM
GROUP BY EMP_NUM, EMP_LNAME
ORDER BY EMP_NUM;