INSERT INTO EMP_1 (EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
SELECT 
    EMP_NUM,
    EMP_LNAME,
    EMP_FNAME,
    EMP_INITIAL,
    EMP_HIREDATE,
    JOB_CODE
FROM 
    EMPLOYEE
WHERE 
    EMP_NUM IN ('103','104','105','106','107','108','109');